name: gm
channels:
    - defaults
    - conda-forge
    - pytorch
    - nvidia
dependencies:
    - python
    - keyboard
    - numpy
    - scipy
    - pandas
    - matplotlib
    - gym
    - tensorboard
    - pytorch
    - torchvision
    - torchaudio
    - pytorch-cuda